image: mcr.microsoft.com/devcontainers/base:ubuntu

tasks:
  - name: Setup Flutter
    init: |
      sudo apt update && sudo apt install -y curl git unzip xz-utils zip libglu1-mesa
      git clone https://github.com/flutter/flutter.git -b stable
      echo 'export PATH="$PATH:/workspace/flutter/bin"' >> ~/.bashrc
      export PATH="$PATH:/workspace/flutter/bin"
      flutter doctor
    command: |
      export PATH="$PATH:/workspace/flutter/bin"
      flutter pub get
      flutter run -d chrome

ports:
  - port: 5000
    onOpen: open-preview
