// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb-hAe9FUM9uxTI6EPAT42Jchtws7B6ww',
    appId: '1:148866584693:web:a92980f734fb16c872a83c',
    messagingSenderId: '148866584693',
    projectId: 'quran-hadith-app',
    authDomain: 'quran-hadith-app.firebaseapp.com',
    storageBucket: 'quran-hadith-app.firebasestorage.app',
    measurementId: 'G-21SSN3H9YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzb-YdCPUPWJJN7nUl3rDi0fv1PwCMx0k',
    appId: '1:148866584693:android:c643e58654b67a1072a83c',
    messagingSenderId: '148866584693',
    projectId: 'quran-hadith-app',
    storageBucket: 'quran-hadith-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDElQ_OVxxPmCM7eG9P3E6H6w2zUQJ0kMI',
    appId: '1:148866584693:ios:23307a3bb010741e72a83c',
    messagingSenderId: '148866584693',
    projectId: 'quran-hadith-app',
    storageBucket: 'quran-hadith-app.firebasestorage.app',
    iosBundleId: 'com.example.quranHadithApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDElQ_OVxxPmCM7eG9P3E6H6w2zUQJ0kMI',
    appId: '1:148866584693:ios:23307a3bb010741e72a83c',
    messagingSenderId: '148866584693',
    projectId: 'quran-hadith-app',
    storageBucket: 'quran-hadith-app.firebasestorage.app',
    iosBundleId: 'com.example.quranHadithApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb-hAe9FUM9uxTI6EPAT42Jchtws7B6ww',
    appId: '1:148866584693:web:c9ce1457189e75ea72a83c',
    messagingSenderId: '148866584693',
    projectId: 'quran-hadith-app',
    authDomain: 'quran-hadith-app.firebaseapp.com',
    storageBucket: 'quran-hadith-app.firebasestorage.app',
    measurementId: 'G-QDTFD5G05J',
  );
}
